=== wangyishuo123/DB532/cse532p3-wangyishuo123-wang/CSE532.xsd
<!--
I pledge my honor that all parts of this project were done by me alone and
without collaboration with anybody else.

CSE532 - Project 3
File name: CSE532.xsd
Author: Yishuo Wang (108533945)
Brief description: CSE532.xsd is the xml schema
-->
<xs:schema xmlns="http://localhost:8080/exist/CSE532" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://localhost:8080/exist/CSE532">
    <xs:element name="OId" type="xs:string"/>
    <xs:element name="CId" type="xs:string"/>
    <xs:element name="SId" type="xs:string"/>
    <xs:element name="AId" type="xs:string"/>
    <xs:element name="JId" type="xs:string"/>
    <xs:element name="Name" type="xs:string"/>
    <xs:element name="Date" type="xs:date"/>
    <xs:element name="Score" type="xs:positiveInteger"/>

    

    <xs:element name="Artwork">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="AId"/>
                <xs:element ref="Name"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="Show">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="SId"/>
                <xs:element ref="Date"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="Judge">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="JId"/>
                <xs:element ref="Name"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="Audition">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Score"/>
                <xs:element ref="Show"/>
                <xs:element ref="Artwork"/>
                <xs:element ref="Judge"/>
                
            </xs:sequence>
        </xs:complexType>
    </xs:element>


    <xs:element name="Contestant">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="CId"/>
                <xs:element ref="Name"/>
                <xs:element ref="Audition" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>


    <xs:element name="CSE532">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Contestant" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
        
        <!-- Definition of keys -->
        <xs:key name="PrimaryKeyForContestant">
            <xs:selector xpath="Contestant"/>
            <xs:field xpath="CId"/>
        </xs:key>
        <xs:key name="PrimaryKeyForShow">
            <xs:selector xpath="Show"/>
            <xs:field xpath="SId"/>
        </xs:key>
        <xs:key name="PrimaryKeyForArtwork">
            <xs:selector xpath="Artwork"/>
            <xs:field xpath="AId"/>
        </xs:key>
        <xs:key name="PrimaryKeyForJudge">
            <xs:selector xpath="Judge"/>
            <xs:field xpath="JId"/>
        </xs:key>
        <xs:key name="PrimaryKeyForAudition">
            <xs:selector xpath="Audition"/>
            <xs:field xpath="Show"/>
            <xs:field xpath="Artwork"/>
            <xs:field xpath="Judge"/>
            
        </xs:key>

        <xs:keyref name="FKShow" refer="PrimaryKeyForShow">
            <xs:selector xpath="Audition/Show"/>
            <xs:field xpath="SId"/>
        </xs:keyref>
        <xs:keyref name="FKArtwork" refer="PrimaryKeyForArtwork">
            <xs:selector xpath="Audition/Artwork"/>
            <xs:field xpath="AId"/>
        </xs:keyref>
        <xs:keyref name="FKJudge" refer="PrimaryKeyForJudge">
            <xs:selector xpath="Audition/Judge"/>
            <xs:field xpath="JId"/>
        </xs:keyref>
    </xs:element>
</xs:schema>

=== wangyishuo123/DB532/cse532p3-wangyishuo123-wang/CSE532.xml
<!--
I pledge my honor that all parts of this project were done by me alone and
without collaboration with anybody else.

CSE532 - Project 3
File name: CSE532.xml
Author: Yishuo Wang (108533945)
Brief description: CSE532.xml have all the data in
-->
<CSE532 xmlns="http://localhost:8080/exist/CSE532" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://localhost:8080/exist/CSE532 CSE532.xsd">

    <Contestant>
        <CId>c1</CId>
        <Name>Joe</Name>
        <Audition>
            <Score>7</Score>
            <Show>
                <SId>s1</SId>
                <Date>2014-02-02</Date>
            </Show>
            <Artwork>
                <AId>a1</AId>
                <Name>Barcarolle</Name>
            </Artwork>
            <Judge>
                <JId>j1</JId>
                <Name>Judy</Name>
            </Judge>
        </Audition>

        <Audition>
            <Score>8</Score>
            <Show>
                <SId>s1</SId>
                <Date>2014-02-02</Date>
            </Show>
            <Artwork>
                <AId>a1</AId>
                <Name>Barcarolle</Name>
            </Artwork>
            <Judge>
                <JId>j2</JId>
                <Name>Lucy</Name>
            </Judge>
        </Audition>

        <Audition>
            <Score>6</Score>
            <Show>
                <SId>s1</SId>
                <Date>2014-02-02</Date>
            </Show>
            <Artwork>
                <AId>a1</AId>
                <Name>Barcarolle</Name>
            </Artwork>
            <Judge>
                <JId>j3</JId>
                <Name>Irving</Name>
            </Judge>
        </Audition>

        <Audition>
            <Score>7</Score>
            <Show>
                <SId>s4</SId>
                <Date>2014-08-02</Date>
            </Show>
            <Artwork>
                <AId>a3</AId>
                <Name>Bumblebee</Name>
            </Artwork>
            <Judge>
                <JId>j2</JId>
                <Name>Lucy</Name>
            </Judge>
        </Audition>
        
        <Audition>
            <Score>6</Score>
            <Show>
                <SId>s4</SId>
                <Date>2014-08-02</Date>
            </Show>
            <Artwork>
                <AId>a3</AId>
                <Name>Bumblebee</Name>
            </Artwork>
            <Judge>
                <JId>j5</JId>
                <Name>Oscar</Name>
            </Judge>
        </Audition>
    </Contestant>

    <Contestant>
        <CId>c2</CId>
        <Name>Bob</Name>
        <Audition>
            <Score>8</Score>
            <Show>
                <SId>s2</SId>
                <Date>2014-04-02</Date>
            </Show>
            <Artwork>
                <AId>a5</AId>
                <Name>Swan Lake</Name>
            </Artwork>
            <Judge>
                <JId>j1</JId>
                <Name>Judy</Name>
            </Judge>
        </Audition>

        <Audition>
            <Score>6</Score>
            <Show>
                <SId>s2</SId>
                <Date>2014-04-02</Date>
            </Show>
            <Artwork>
                <AId>a5</AId>
                <Name>Swan Lake</Name>
            </Artwork>
            <Judge>
                <JId>j4</JId>
                <Name>Phil</Name>
            </Judge>
        </Audition>
        
        <Audition>
            <Score>8</Score>
            <Show>
                <SId>s3</SId>
                <Date>2014-06-05</Date>
            </Show>
            <Artwork>
                <AId>a3</AId>
                <Name>Bumblebee</Name>
            </Artwork>
            <Judge>
                <JId>j3</JId>
                <Name>Irving</Name>
            </Judge>
        </Audition>
        <Audition>
            <Score>7</Score>
            <Show>
                <SId>s3</SId>
                <Date>2014-06-05</Date>
            </Show>
            <Artwork>
                <AId>a3</AId>
                <Name>Bumblebee</Name>
            </Artwork>
            <Judge>
                <JId>j4</JId>
                <Name>Phil</Name>
            </Judge>
        </Audition>
        <Audition>
            <Score>9</Score>
            <Show>
                <SId>s3</SId>
                <Date>2014-06-05</Date>
            </Show>
            <Artwork>
                <AId>a3</AId>
                <Name>Bumblebee</Name>
            </Artwork>
            <Judge>
                <JId>j5</JId>
                <Name>Oscar</Name>
            </Judge>
        </Audition>

        <Audition>
            <Score>6</Score>
            <Show>
                <SId>s4</SId>
                <Date>2014-08-02</Date>
            </Show>
            <Artwork>
                <AId>a1</AId>
                <Name>Barcarolle</Name>
            </Artwork>
            <Judge>
                <JId>j2</JId>
                <Name>Lucy</Name>
            </Judge>
        </Audition>
        <Audition>
            <Score>8</Score>
            <Show>
                <SId>s4</SId>
                <Date>2014-08-02</Date>
            </Show>
            <Artwork>
                <AId>a1</AId>
                <Name>Barcarolle</Name>
            </Artwork>
            <Judge>
                <JId>j5</JId>
                <Name>Oscar</Name>
            </Judge>
        </Audition>

        <Audition>
            <Score>3</Score>
            <Show>
                <SId>s5</SId>
                <Date>2014-06-05</Date>
            </Show>
            <Artwork>
                <AId>a5</AId>
                <Name>Swan Lake</Name>
            </Artwork>
            <Judge>
                <JId>j2</JId>
                <Name>Lucy</Name>
            </Judge>
        </Audition>
        <Audition>
            <Score>5</Score>
            <Show>
                <SId>s5</SId>
                <Date>2014-06-05</Date>
            </Show>
            <Artwork>
                <AId>a5</AId>
                <Name>Swan Lake</Name>
            </Artwork>
            <Judge>
                <JId>j3</JId>
                <Name>Irving</Name>
            </Judge>
        </Audition>
        <Audition>
            <Score>6</Score>
            <Show>
                <SId>s5</SId>
                <Date>2014-06-05</Date>
            </Show>
            <Artwork>
                <AId>a5</AId>
                <Name>Swan Lake</Name>
            </Artwork>
            <Judge>
                <JId>j4</JId>
                <Name>Phil</Name>
            </Judge>
        </Audition>

        <Audition>
            <Score>4</Score>
            <Show>
                <SId>s5</SId>
                <Date>2014-06-05</Date>
            </Show>
            <Artwork>
                <AId>a2</AId>
                <Name>Giselle</Name>
            </Artwork>
            <Judge>
                <JId>j2</JId>
                <Name>Lucy</Name>
            </Judge>
        </Audition>
        <Audition>
            <Score>6</Score>
            <Show>
                <SId>s5</SId>
                <Date>2014-06-05</Date>
            </Show>
            <Artwork>
                <AId>a2</AId>
                <Name>Giselle</Name>
            </Artwork>
            <Judge>
                <JId>j3</JId>
                <Name>Irving</Name>
            </Judge>
        </Audition>
        <Audition>
            <Score>8</Score>
            <Show>
                <SId>s5</SId>
                <Date>2014-06-05</Date>
            </Show>
            <Artwork>
                <AId>a2</AId>
                <Name>Giselle</Name>
            </Artwork>
            <Judge>
                <JId>j4</JId>
                <Name>Phil</Name>
            </Judge>
        </Audition>
    </Contestant>

    <Contestant>
        <CId>c3</CId>
        <Name>Mary</Name>
        <Audition>
            <Score>5</Score>
            <Show>
                <SId>s1</SId>
                <Date>2014-02-02</Date>
            </Show>
            <Artwork>
                <AId>a1</AId>
                <Name>Barcarolle</Name>
            </Artwork>
            <Judge>
                <JId>j1</JId>
                <Name>Judy</Name>
            </Judge>
        </Audition>
        <Audition>
            <Score>6</Score>
            <Show>
                <SId>s1</SId>
                <Date>2014-02-02</Date>
            </Show>
            <Artwork>
                <AId>a1</AId>
                <Name>Barcarolle</Name>
            </Artwork>
            <Judge>
                <JId>j2</JId>
                <Name>Lucy</Name>
            </Judge>
        </Audition>
        <Audition>
            <Score>6</Score>
            <Show>
                <SId>s1</SId>
                <Date>2014-02-02</Date>
            </Show>
            <Artwork>
                <AId>a1</AId>
                <Name>Barcarolle</Name>
            </Artwork>
            <Judge>
                <JId>j3</JId>
                <Name>Irving</Name>
            </Judge>
        </Audition>
        <Audition>
            <Score>9</Score>
            <Show>
                <SId>s1</SId>
                <Date>2014-02-02</Date>
            </Show>
            <Artwork>
                <AId>a2</AId>
                <Name>Giselle</Name>
            </Artwork>
            <Judge>
                <JId>j1</JId>
                <Name>Judy</Name>
            </Judge>
        </Audition>
        <Audition>
            <Score>6</Score>
            <Show>
                <SId>s1</SId>
                <Date>2014-02-02</Date>
            </Show>
            <Artwork>
                <AId>a2</AId>
                <Name>Giselle</Name>
            </Artwork>
            <Judge>
                <JId>j2</JId>
                <Name>Lucy</Name>
            </Judge>
        </Audition>
        <Audition>
            <Score>8</Score>
            <Show>
                <SId>s1</SId>
                <Date>2014-02-02</Date>
            </Show>
            <Artwork>
