=== wangyishuo123/DB532/cse532p3-wangyishuo123-wang/old relational version/CSE532.xsd
<xs:schema xmlns="http://localhost:8080/exist/CSE532" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://localhost:8080/exist/CSE532">
    <xs:element name="CId" type="xs:string"/>
    <xs:element name="SId" type="xs:string"/>
    <xs:element name="AId" type="xs:string"/>
    <xs:element name="JId" type="xs:string"/>
    <xs:element name="Name" type="xs:string"/>
    <xs:element name="Date" type="xs:date"/>
    <xs:element name="Score" type="xs:positiveInteger"/>

    <xs:element name="Contestant">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="CId"/>
                <xs:element ref="Name"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="Artwork">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="AId"/>
                <xs:element ref="Name"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="Show">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="SId"/>
                <xs:element ref="Date"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="Judge">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="JId"/>
                <xs:element ref="Name"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>  
    <xs:element name="Audition">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Score" maxOccurs="10" minOccurs="0"/>
                <xs:element ref="CId"/>
                <xs:element ref="AId"/>
                <xs:element ref="SId"/>
                <xs:element ref="JId"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element> 

    <xs:element name="Contestants">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Contestant" maxOccurs="unbounded" minOccurs="0"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="Shows">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Show" maxOccurs="unbounded" minOccurs="0"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element> 
    <xs:element name="Artworks">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Artwork" maxOccurs="unbounded" minOccurs="0"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element> 
    <xs:element name="Judges">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Judge" maxOccurs="unbounded" minOccurs="0"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element> 
    <xs:element name="Auditions">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Audition" maxOccurs="unbounded" minOccurs="0"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element> 

    <xs:element name="CSE532">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Contestants"/>
                <xs:element ref="Shows"/>
                <xs:element ref="Artworks"/>
                <xs:element ref="Judges"/>
                <xs:element ref="Auditions"/>
            </xs:sequence>
        </xs:complexType>
        
        <!-- Definition of keys -->
        <xs:key name="PrimaryKeyForContestant">
            <xs:selector xpath="Contestant"/>
            <xs:field xpath="CId"/>
        </xs:key>

        <xs:key name="PrimaryKeyForShow">
            <xs:selector xpath="Show"/>
            <xs:field xpath="SId"/>
        </xs:key>

        <xs:key name="PrimaryKeyForArtwork">
            <xs:selector xpath="Artwork"/>
            <xs:field xpath="AId"/>
        </xs:key>

        <xs:key name="PrimaryKeyForJudge">
            <xs:selector xpath="Judge"/>
            <xs:field xpath="JId"/>
        </xs:key>

        <xs:key name="PrimaryKeyForAudition">
            <xs:selector xpath="Audition"/>
            <xs:field xpath="CId"/>
            <xs:field xpath="SId"/>
            <xs:field xpath="AId"/>
            <xs:field xpath="JId"/>
        </xs:key>

        <xs:keyref name="FKContestant" refer="PrimaryKeyForContestant">
            <xs:selector xpath="Audition"/>
            <xs:field xpath="CId"/>
        </xs:keyref>

        <xs:keyref name="FKShow" refer="PrimaryKeyForShow">
            <xs:selector xpath="Audition"/>
            <xs:field xpath="SId"/>
        </xs:keyref>

        <xs:keyref name="FKArtwork" refer="PrimaryKeyForArtwork">
            <xs:selector xpath="Audition"/>
            <xs:field xpath="AId"/>
        </xs:keyref>

        <xs:keyref name="FKJudge" refer="PrimaryKeyForJudge">
            <xs:selector xpath="Audition"/>
            <xs:field xpath="JId"/>
        </xs:keyref>
    </xs:element>
</xs:schema>

=== wangyishuo123/DB532/cse532p3-wangyishuo123-wang/old relational version/CSE532.xml
<CSE532 xmlns="http://localhost:8080/exist/CSE532" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://localhost:8080/exist/CSE532 CSE532.xsd">
    <!-- Contestant -->
    <Contestants>
        <Contestant>
            <CId>c1</CId>
            <Name>Joe</Name>
        </Contestant>

        <Contestant>
            <CId>c2</CId>
            <Name>Bob</Name>
        </Contestant>

        <Contestant>
            <CId>c3</CId>
            <Name>Mary</Name>
        </Contestant>

        <Contestant>
            <CId>c4</CId>
            <Name>Bess</Name>
        </Contestant>

        <Contestant>
            <CId>c5</CId>
            <Name>Tom</Name>
        </Contestant>

        <Contestant>
            <CId>c6</CId>
            <Name>Don</Name>
        </Contestant>

        <Contestant>
            <CId>c7</CId>
            <Name>Ann</Name>
        </Contestant>
    </Contestants>
    
    <!-- Show -->
    <Shows>
        <Show>
            <SId>s1</SId>
            <Date>2014-02-02</Date>
        </Show>
        <Show>
            <SId>s2</SId>
            <Date>2014-04-02</Date>
        </Show>
        <Show>
            <SId>s3</SId>
            <Date>2014-06-05</Date>
        </Show>
        <Show>
            <SId>s4</SId>
            <Date>2014-08-02</Date>
        </Show>
        <Show>
            <SId>s5</SId>
            <Date>2014-06-05</Date>
        </Show>
    </Shows>

    
    <!-- Artwork -->
    <Artworks>
        <Artwork>
            <AId>a1</AId>
            <Name>Barcarolle</Name>
        </Artwork>
        <Artwork>
            <AId>a2</AId>
            <Name>Giselle</Name>
        </Artwork>
        <Artwork>
            <AId>a3</AId>
            <Name>Bumblebee</Name>
        </Artwork>
        <Artwork>
            <AId>a4</AId>
            <Name>Besame Mucho</Name>
        </Artwork>
        <Artwork>
            <AId>a5</AId>
            <Name>Swan Lake</Name>
        </Artwork>
        <Artwork>
            <AId>a6</AId>
            <Name>Habanera</Name>
        </Artwork>
    </Artworks>
    <!-- Judge -->
    <Judges>
        <Judge>
            <JId>j1</JId>
            <Name>Judy</Name>
        </Judge>
        <Judge>
            <JId>j2</JId>
            <Name>Lucy</Name>
        </Judge>
        <Judge>
            <JId>j3</JId>
            <Name>Irving</Name>
        </Judge>
        <Judge>
            <JId>j4</JId>
            <Name>Phil</Name>
        </Judge>
        <Judge>
            <JId>j5</JId>
            <Name>Oscar</Name>
        </Judge>
    </Judges>
    <!-- Audition -->
    <Auditions>
        <Audition>
            <Score>7</Score>
            <CId>c1</CId>
            <AId>a1</AId>
            <SId>s1</SId>
            <JId>j1</JId>
        </Audition>
        <Audition>
            <Score>8</Score>
            <CId>c1</CId>
            <AId>a1</AId>
            <SId>s1</SId>
            <JId>j2</JId>
        </Audition>
        <Audition>
            <Score>6</Score>
            <CId>c1</CId>
            <AId>a1</AId>
            <SId>s1</SId>
            <JId>j3</JId>
        </Audition>

        <Audition>
            <Score>5</Score>
            <CId>c3</CId>
            <AId>a1</AId>
            <SId>s1</SId>
            <JId>j1</JId>
        </Audition>
        <Audition>
            <Score>6</Score>
            <CId>c3</CId>
            <AId>a1</AId>
            <SId>s1</SId>
            <JId>j2</JId>
        </Audition>
        <Audition>
            <Score>6</Score>
            <CId>c3</CId>
            <AId>a1</AId>
            <SId>s1</SId>
            <JId>j3</JId>
        </Audition>

        <Audition>
            <Score>9</Score>
            <CId>c3</CId>
            <AId>a2</AId>
            <SId>s1</SId>
            <JId>j1</JId>
        </Audition>
        <Audition>
            <Score>6</Score>
            <CId>c3</CId>
            <AId>a2</AId>
            <SId>s1</SId>
            <JId>j2</JId>
        </Audition>
        <Audition>
            <Score>8</Score>
            <CId>c3</CId>
            <AId>a2</AId>
            <SId>s1</SId>
            <JId>j3</JId>
        </Audition>

        <Audition>
            <Score>4</Score>
            <CId>c4</CId>
            <AId>a4</AId>
            <SId>s1</SId>
            <JId>j1</JId>
        </Audition>
        <Audition>
            <Score>5</Score>
            <CId>c4</CId>
            <AId>a4</AId>
            <SId>s1</SId>
            <JId>j2</JId>
        </Audition>
        <Audition>
            <Score>6</Score>
            <CId>c4</CId>
            <AId>a4</AId>
            <SId>s1</SId>
            <JId>j3</JId>
        </Audition>

        <Audition>
            <Score>9</Score>
            <CId>c6</CId>
            <AId>a4</AId>
            <SId>s1</SId>
            <JId>j1</JId>
        </Audition>
        <Audition>
            <Score>9</Score>
            <CId>c6</CId>
            <AId>a4</AId>
            <SId>s1</SId>
            <JId>j2</JId>
        </Audition>
        <Audition>
            <Score>7</Score>
            <CId>c6</CId>
            <AId>a4</AId>
            <SId>s1</SId>
            <JId>j3</JId>
        </Audition>

        <Audition>
            <Score>7</Score>
            <CId>c6</CId>
            <AId>a5</AId>
            <SId>s1</SId>
            <JId>j1</JId>
        </Audition>
        <Audition>
            <Score>7</Score>
            <CId>c6</CId>
            <AId>a5</AId>
            <SId>s1</SId>
            <JId>j2</JId>
        </Audition>
        <Audition>
            <Score>10</Score>
            <CId>c6</CId>
            <AId>a5</AId>
            <SId>s1</SId>
            <JId>j3</JId>
        </Audition>



        <Audition>
            <Score>8</Score>
            <CId>c2</CId>
            <AId>a5</AId>
            <SId>s2</SId>
            <JId>j1</JId>
        </Audition>
        <Audition>
            <Score>6</Score>
            <CId>c2</CId>
            <AId>a5</AId>
            <SId>s2</SId>
            <JId>j4</JId>
        </Audition>

        <Audition>
            <Score>3</Score>
            <CId>c3</CId>
            <AId>a6</AId>
            <SId>s2</SId>
            <JId>j1</JId>
        </Audition>
        <Audition>
            <Score>5</Score>
            <CId>c3</CId>
            <AId>a6</AId>
            <SId>s2</SId>
            <JId>j4</JId>
        </Audition>

        <Audition>
            <Score>9</Score>
            <CId>c3</CId>
            <AId>a4</AId>
            <SId>s2</SId>
            <JId>j1</JId>
        </Audition>
        <Audition>
            <Score>10</Score>
            <CId>c3</CId>
            <AId>a4</AId>
            <SId>s2</SId>
            <JId>j4</JId>
        </Audition>

        <Audition>
            <Score>7</Score>
            <CId>c7</CId>
            <AId>a6</AId>
            <SId>s2</SId>
            <JId>j1</JId>
        </Audition>
        <Audition>
            <Score>6</Score>
            <CId>c7</CId>
            <AId>a6</AId>
            <SId>s2</SId>
            <JId>j4</JId>
        </Audition>

        <Audition>
            <Score>8</Score>
            <CId>c4</CId>
            <AId>a2</AId>
            <SId>s2</SId>
            <JId>j1</JId>
        </Audition>
        <Audition>
            <Score>7</Score>
            <CId>c4</CId>
            <AId>a2</AId>
            <SId>s2</SId>
            <JId>j4</JId>
        </Audition>

        <Audition>
            <Score>5</Score>
            <CId>c5</CId>
            <AId>a4</AId>
            <SId>s2</SId>
            <JId>j1</JId>
        </Audition>
        <Audition>
            <Score>5</Score>
            <CId>c5</CId>
            <AId>a4</AId>
            <SId>s2</SId>
            <JId>j4</JId>
        </Audition>

        <Audition>
            <Score>7</Score>
            <CId>c5</CId>
            <AId>a3</AId>
            <SId>s2</SId>
            <JId>j1</JId>
        </Audition>
        <Audition>
            <Score>6</Score>
            <CId>c5</CId>
            <AId>a3</AId>
            <SId>s2</SId>
            <JId>j4</JId>
        </Audition>



        <Audition>
            <Score>8</Score>
            <CId>c2</CId>
            <AId>a3</AId>
            <SId>s3</SId>
            <JId>j3</JId>
        </Audition>
        <Audition>
            <Score>7</Score>
            <CId>c2</CId>
            <AId>a3</AId>
            <SId>s3</SId>
            <JId>j4</JId>
        </Audition>
        <Audition>
            <Score>9</Score>
            <CId>c2</CId>
            <AId>a3</AId>
            <SId>s3</SId>
            <JId>j5</JId>
        </Audition>

        <Audition>
            <Score>7</Score>
            <CId>c7</CId>
            <AId>a4</AId>
            <SId>s3</SId>
            <JId>j3</JId>
        </Audition>
        <Audition>
            <Score>6</Score>
            <CId>c7</CId>
            <AId>a4</AId>
            <SId>s3</SId>
            <JId>j4</JId>
        </Audition>
        <Audition>
            <Score>4</Score>
            <CId>c7</CId>
            <AId>a4</AId>
            <SId>s3</SId>
            <JId>j5</JId>
        </Audition>

        <Audition>
            <Score>6</Score>
            <CId>c4</CId>
            <AId>a5</AId>
            <SId>s3</SId>
            <JId>j3</JId>
        </Audition>
        <Audition>
            <Score>8</Score>
            <CId>c4</CId>
            <AId>a5</AId>
            <SId>s3</SId>
            <JId>j4</JId>
        </Audition>
        <Audition>
            <Score>7</Score>
            <CId>c4</CId>
            <AId>a5</AId>
            <SId>s3</SId>
            <JId>j5</JId>
        </Audition>

        <Audition>
            <Score>9</Score>
            <CId>c5</CId>
            <AId>a1</AId>
            <SId>s3</SId>
            <JId>j3</JId>
        </Audition>
        <Audition>
            <Score>7</Score>
            <CId>c5</CId>
            <AId>a1</AId>
            <SId>s3</SId>
